---
name: Run tests

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'resources/**'
      - '.github/workflows/clojure.yaml'
      - 'build.clj'
      - 'deps.edn'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'resources/**'
      - '.github/workflows/clojure.yaml'
      - 'build.clj'
      - 'deps.edn'
jobs:
  build-clj:
    strategy:
      matrix:
        # Supported Java versions: LTS releases and latest
        jdk: [8, 11, 17, 21]
        clojure: [12]

    name: Clojure ${{ matrix.clojure }} (Java ${{ matrix.jdk }})

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.jdk }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-test-deps-${{ hashFiles('**/deps.edn') }}-${{ matrix.clojure }}-${{ matrix.jdk }}
          restore-keys: |
            ${{ runner.os }}-test-deps-${{ hashFiles('**/deps.edn') }}-${{ matrix.clojure }}-
            ${{ runner.os }}-test-deps-
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - name: Run tests
        run: clojure -T:build ci